name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Crear archivo .env
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env

      - name: Checkout código
        uses: actions/checkout@v3

      - name: Usar Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependencias
        run: npm install

      - name: Validar código (opcional)
        run: |
          echo "No lint configured"  # Reemplaza con eslint si tienes

      - name: Ejecutar pruebas (opcional)
        run: |
          echo "No tests configured"  # Reemplaza con npm test si usas testing

      - name: Verificar que compila
        run: node src/app.js &
